const staffBios = [
    {
        "id": "1",
        "firstName": "Melissa",
        "lastName": "Longenberger",
        "photo": "https://i.ibb.co/vc3Dw0b/new-melissa.jpg",
        "position": "CEO & Founder",
        "location": "Berwick, PA",
        "about": "Full Stack software Developer, Navy Veteran, Gardener and Crocheter with a passion for creating.",
        "technologies": ["HTML", "CSS", "JavaScript", "LESS", "React", "Vite", "Express.js", "Node", "Next.js", "Java", "C#", "Python", "SQL", "PostgreSQL", "Mongo", "Pug", "Django", "Flask", "Git", "Github"],
        "isMentor": true,
        "isTutor": true,
        "isInstructor": true,
        "isTA": false,
        "isActive": true
    },
    {
        "id": "2",
        "firstName": "Christopher",
        "lastName": "Jones",
        "photo": "",
        "position": "Position: TBD",
        "location": "Plano, TX",
        "about": "Software developer with a flair for crafting creative code.",
        "technologies": ["HTML", "CSS", "JS", "React", "Next.js", "Django", "Python", "VS Code", "Git", "GitHub", "SQLite"],
        "isMentor": true,
        "isTutor": true,
        "isInstructor": true,
        "isTA": false,
        "isActive": true
    },
    {
        "id": "3",
        "firstName": "Brent",
        "lastName": "Cleary",
        "photo": "",
        "position": "Position: TBD",
        "location": "Seattle, WA",
        "about": "Full Stack Software Developer with an emphasis in C#",
        "technologies": ["HTML", "CSS", "JavaScript", "C#", "React", "Next.js", "Python", "VS Code", "Git", "GitHub", "PostgresSQL"],
        "isMentor": true,
        "isTutor": true,
        "isInstructor": true,
        "isTA": false,
        "isActive": true
    },
    {
        "id": "4",
        "firstName": "Chris",
        "lastName": "Bridgewater",
        "photo": "https://i.ibb.co/HXQV9gS/chris-bridgewater.jpg",
        "position": "Position: TBD",
        "location": "Creswell, OR",
        "about": "Full Stack Software Developer. If I’m not on my computer, I’m enjoying the outdoors!",
        "technologies": ["HTML", "CSS", "JavaScript", "React", "Express.js", "Node.js", "Java", "Python", "Flask", "Django", "C#", "ASP.NET", "VS Code", "Spring Boot", "Git", "GitHub", "MongoDB", "MySQL", "AWS EC2"],
        "isMentor": true,
        "isTutor": true,
        "isInstructor": true,
        "isTA": false,
        "isActive": true
    },
    {
        "id": "5",
        "firstName": "Abrar",
        "lastName": "Hussain",
        "photo": "https://i.ibb.co/vHxB3nL/abrar.jpg",
        "position": "Position: TBD",
        "location": "Chicago, IL",
        "about": "Full Stack Engineer | If I'm not on my computer, I'm most likely at the gym!",
        "technologies": ["JavaScript", "React", "Next JS", "MERN", "Firebase", "Java", "Spring", "Python", "Git", "GitHub", "MySQL"],
        "isMentor": true,
        "isTutor": true,
        "isInstructor": true,
        "isTA": false,
        "isActive": true
    },
    {
        "id": "6",
        "firstName": "Marc",
        "lastName": "Boisvert",
        "photo": "",
        "position": "Position: TBD",
        "location": "Vine Grove, Kentucky",
        "about": "No idea what to fill out for me :)",
        "technologies": [],
        "isMentor": false,
        "isTutor": false,
        "isInstructor": false,
        "isTA": false,
        "isActive": false
    },
    {
        "id": "7",
        "firstName": "Kyle",
        "lastName": "Rohr-Morey",
        "photo": "",
        "position": "Position: TBD",
        "location": "Wethersfield, Connecticut",
        "about": "Frontend Development | Game Development for over 4+ years!",
        "technologies": ["HTML", "CSS", "JavaScript", "TypeScript", "React", "Canvas API", "Phaser 3", "Express.js", "Mongoose", "MongoDB", "Node.js", "Electron", "Git", "GitHub"],
        "isMentor": true,
        "isTutor": true,
        "isInstructor": true,
        "isTA": false,
        "isActive": true
    },
    {
        "id": "8",
        "firstName": "Luis",
        "lastName": "Hernandez",
        "photo": "",
        "position": "Position: TBD",
        "location": "Seattle, Wa",
        "about": "Full Stack Software Developer",
        "technologies": ["HTML", "CSS", "JavaScript", "React", "Express.js", "Node.js", "Python", "Flask", "Django", "Java", "Spring Boot", "Linux", "MySQL", "MongoDB", "Git", "GitHub", "AWS EC2"],
        "isMentor": true,
        "isTutor": true,
        "isInstructor": true,
        "isTA": false,
        "isActive": true
    }
];

export default staffBios;
